### ISSUE TITLE
message_handler  no work

### ISSUE THREAD

**Issue by pureloveljc** [binance/binance-connector-python#174] opened 2022-10-04 02:02 UTC
import time
import logging
from binance.lib.utils import config_logging
from binance.websocket.um_futures.websocket_client import UMFuturesWebsocketClient

config_logging(logging, logging.DEBUG)

def message_handler(message):
    print(message)

my_client = UMFuturesWebsocketClient()
my_client.start()

my_client.kline(
    symbol="btcusdt",
    id=12,
    interval="1d",
    callback=message_handler,
)

time.sleep(10)

logging.debug("closing ws connection")
my_client.stop()

this is output:
![image](https://user-images.githubusercontent.com/32063794/193718643-21a8a9eb-f997-46bb-9f05-bf45b6e64b37.png)

**Comment by 2pd** [comment] 2022-10-06 10:29
duplicate of https://github.com/binance/binance-futures-connector-python/issues/55

**Closed by 2pd** 2022-10-06 10:29 UTC
