### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000306BFA9340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### ISSUE THREAD

**Issue by knowledgecomputer2018** [binance/binance-connector-python#66] opened 2021-07-15 08:39 UTC
hi how are you

i have a error to request to binance but i request with colab google have not error and ok .
thank you very much for reply me about error 

i search very much in multiple website 

good luck 
god willing

**Comment by aisling11** [comment] 2021-07-16 15:41
Hi @knowledgecomputer2018, at first this seems to be network issue at your end, maybe caused by firewall.
However, if it's still happening, you can share your code example so we can see if we can replicate and investigate further.

**Comment by knowledgecomputer2018** [comment] 2021-07-16 16:41
hi

 my code is ping to website binance by API_KEY,SECRET_KEY.my code is correct because i run code over colab google is good but i run my system this is my problem . i  turn off my firewall no different and i change port 9443 to open port but not change .

good luck 
god willing

**Comment by aisling11** [comment] 2021-07-20 16:46
Hi @knowledgecomputer2018, please share the steps to reproduce this on our side, at the moment we don't have enough details to help you further.

**Comment by aisling11** [comment] 2021-07-22 10:10
Hi @knowledgecomputer2018 since there's no further updates, allow me to close the issue for now, but please feel free to re-open if necessary.

**Closed by aisling11** 2021-07-22 10:10 UTC
